# /home/juma-samwel-onyango/Software Engineering Intern Task/afiya_system/afiya/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProgramViewSet, ClientViewSet

# DRF Routers provide an easy way of automatically determining the URL conf.
# This router maps HTTP methods to the appropriate actions defined in the ViewSets.
router = DefaultRouter()

# Register the ViewSets with the router.
# 'programs' is the URL prefix for Program related endpoints.
# 'clients' is the URL prefix for Client related endpoints.
# 'basename' is used to generate URL names.
router.register(r'programs', ProgramViewSet, basename='program')
router.register(r'clients', ClientViewSet, basename='client')

# The urlpatterns list routes URLs to views.
# The `include(router.urls)` line incorporates all the URLs automatically generated by the DefaultRouter.
# These URLs handle the standard CRUD operations and any custom actions (@action) defined in the ViewSets.
# Examples generated:
#   /programs/
#   /programs/{pk}/
#   /clients/
#   /clients/{pk}/
#   /clients/search/
#   /clients/{pk}/enroll/
urlpatterns = [
    path('', include(router.urls)),
]
