# Generated by Django 5.2 on 2025-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Contact information (e.g., phone number, email).', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(help_text="Client's date of birth."),
        ),
        migrations.AlterField(
            model_name='client',
            name='enrolled_programs',
            field=models.ManyToManyField(blank=True, help_text='Programs this client is enrolled in.', related_name='clients', to='afiya.program'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Full name of the client.', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='The unique name of the health program.', max_length=100, unique=True),
        ),
    ]
